export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  BRANDS: '/catalog/brands',
  SALLER: '/catalog/seller',
  PROFILE: '/profile',
  JOB: '/job',
  CHATS: '/chats',
  MY_VACANCY: '/vacancy/my',
  CREATE_VACANCY: '/vacancy/create',
  EDIT_VACANCY: '/vacancy/edit',
  MY_ADVERTISEMENTS: '/advertisements/my',
  CREATE_ADVERTISEMENT: '/advertisements/create',
  EDIT_ADVERTISEMENT: '/advertisements/edit',
  FAVORITES: '/advertisements/favorites',
  MY_RESUME: '/resume/my',
  CREATE_RESUME: '/resume/create',
  EDIT_RESUME: '/resume/edit',
} as const;
